// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: graph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents an AS node
type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Asn             uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Desc            string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Routes          []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	Centrality      *Centrality            `protobuf:"bytes,4,opt,name=centrality,proto3" json:"centrality,omitempty"`
	RoutesMulticast []*Route               `protobuf:"bytes,5,rep,name=routes_multicast,json=routesMulticast,proto3" json:"routes_multicast,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Node) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Node) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Node) GetCentrality() *Centrality {
	if x != nil {
		return x.Centrality
	}
	return nil
}

func (x *Node) GetRoutesMulticast() []*Route {
	if x != nil {
		return x.RoutesMulticast
	}
	return nil
}

// Centrality stores the centrality metrics of a node
type Centrality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Degree        float64                `protobuf:"fixed64,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Betweenness   float64                `protobuf:"fixed64,2,opt,name=betweenness,proto3" json:"betweenness,omitempty"`
	Closeness     float64                `protobuf:"fixed64,3,opt,name=closeness,proto3" json:"closeness,omitempty"`
	Index         uint32                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"` // dn42Index
	Ranking       uint32                 `protobuf:"varint,5,opt,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Centrality) Reset() {
	*x = Centrality{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Centrality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Centrality) ProtoMessage() {}

func (x *Centrality) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Centrality.ProtoReflect.Descriptor instead.
func (*Centrality) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Centrality) GetDegree() float64 {
	if x != nil {
		return x.Degree
	}
	return 0
}

func (x *Centrality) GetBetweenness() float64 {
	if x != nil {
		return x.Betweenness
	}
	return 0
}

func (x *Centrality) GetCloseness() float64 {
	if x != nil {
		return x.Closeness
	}
	return 0
}

func (x *Centrality) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Centrality) GetRanking() uint32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

// Route represents a route entry
type Route struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Length uint32                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// Types that are valid to be assigned to Ip:
	//
	//	*Route_Ipv4
	//	*Route_Ipv6
	Ip            isRoute_Ip `protobuf_oneof:"ip"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Route) GetIp() isRoute_Ip {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Route) GetIpv4() uint32 {
	if x != nil {
		if x, ok := x.Ip.(*Route_Ipv4); ok {
			return x.Ipv4
		}
	}
	return 0
}

func (x *Route) GetIpv6() *IPv6 {
	if x != nil {
		if x, ok := x.Ip.(*Route_Ipv6); ok {
			return x.Ipv6
		}
	}
	return nil
}

type isRoute_Ip interface {
	isRoute_Ip()
}

type Route_Ipv4 struct {
	Ipv4 uint32 `protobuf:"varint,2,opt,name=ipv4,proto3,oneof"`
}

type Route_Ipv6 struct {
	Ipv6 *IPv6 `protobuf:"bytes,3,opt,name=ipv6,proto3,oneof"`
}

func (*Route_Ipv4) isRoute_Ip() {}

func (*Route_Ipv6) isRoute_Ip() {}

// IPv6 represents an IPv6 address
type IPv6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighH32       uint32                 `protobuf:"varint,1,opt,name=high_h32,json=highH32,proto3" json:"high_h32,omitempty"`
	HighL32       uint32                 `protobuf:"varint,2,opt,name=high_l32,json=highL32,proto3" json:"high_l32,omitempty"`
	LowH32        uint32                 `protobuf:"varint,3,opt,name=low_h32,json=lowH32,proto3" json:"low_h32,omitempty"`
	LowL32        uint32                 `protobuf:"varint,4,opt,name=low_l32,json=lowL32,proto3" json:"low_l32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv6) Reset() {
	*x = IPv6{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6) ProtoMessage() {}

func (x *IPv6) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6.ProtoReflect.Descriptor instead.
func (*IPv6) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *IPv6) GetHighH32() uint32 {
	if x != nil {
		return x.HighH32
	}
	return 0
}

func (x *IPv6) GetHighL32() uint32 {
	if x != nil {
		return x.HighL32
	}
	return 0
}

func (x *IPv6) GetLowH32() uint32 {
	if x != nil {
		return x.LowH32
	}
	return 0
}

func (x *IPv6) GetLowL32() uint32 {
	if x != nil {
		return x.LowL32
	}
	return 0
}

// Link represents a connection between two ASes
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        uint32                 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        uint32                 `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	Af            uint32                 `protobuf:"varint,3,opt,name=af,proto3" json:"af,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

func (x *Link) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Link) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Link) GetAf() uint32 {
	if x != nil {
		return x.Af
	}
	return 0
}

// Contains metadata information about the graph.
type Metadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vendor             string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	GeneratedTimestamp uint64                 `protobuf:"varint,2,opt,name=generated_timestamp,json=generatedTimestamp,proto3" json:"generated_timestamp,omitempty"`
	DataTimestamp      uint64                 `protobuf:"varint,3,opt,name=data_timestamp,json=dataTimestamp,proto3" json:"data_timestamp,omitempty"`
	Version            uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Metadata) GetGeneratedTimestamp() uint64 {
	if x != nil {
		return x.GeneratedTimestamp
	}
	return 0
}

func (x *Metadata) GetDataTimestamp() uint64 {
	if x != nil {
		return x.DataTimestamp
	}
	return 0
}

func (x *Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Graph represents the entire network topology
type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*Link                `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{6}
}

func (x *Graph) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\bdn42_map\"\xc7\x01\n" +
	"\x04Node\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12'\n" +
	"\x06routes\x18\x03 \x03(\v2\x0f.dn42_map.RouteR\x06routes\x124\n" +
	"\n" +
	"centrality\x18\x04 \x01(\v2\x14.dn42_map.CentralityR\n" +
	"centrality\x12:\n" +
	"\x10routes_multicast\x18\x05 \x03(\v2\x0f.dn42_map.RouteR\x0froutesMulticast\"\x94\x01\n" +
	"\n" +
	"Centrality\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\x01R\x06degree\x12 \n" +
	"\vbetweenness\x18\x02 \x01(\x01R\vbetweenness\x12\x1c\n" +
	"\tcloseness\x18\x03 \x01(\x01R\tcloseness\x12\x14\n" +
	"\x05index\x18\x04 \x01(\rR\x05index\x12\x18\n" +
	"\aranking\x18\x05 \x01(\rR\aranking\"a\n" +
	"\x05Route\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12\x14\n" +
	"\x04ipv4\x18\x02 \x01(\rH\x00R\x04ipv4\x12$\n" +
	"\x04ipv6\x18\x03 \x01(\v2\x0e.dn42_map.IPv6H\x00R\x04ipv6B\x04\n" +
	"\x02ip\"n\n" +
	"\x04IPv6\x12\x19\n" +
	"\bhigh_h32\x18\x01 \x01(\rR\ahighH32\x12\x19\n" +
	"\bhigh_l32\x18\x02 \x01(\rR\ahighL32\x12\x17\n" +
	"\alow_h32\x18\x03 \x01(\rR\x06lowH32\x12\x17\n" +
	"\alow_l32\x18\x04 \x01(\rR\x06lowL32\"F\n" +
	"\x04Link\x12\x16\n" +
	"\x06source\x18\x01 \x01(\rR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\rR\x06target\x12\x0e\n" +
	"\x02af\x18\x03 \x01(\rR\x02af\"\x94\x01\n" +
	"\bMetadata\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12/\n" +
	"\x13generated_timestamp\x18\x02 \x01(\x04R\x12generatedTimestamp\x12%\n" +
	"\x0edata_timestamp\x18\x03 \x01(\x04R\rdataTimestamp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\"\x83\x01\n" +
	"\x05Graph\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.dn42_map.MetadataR\bmetadata\x12$\n" +
	"\x05nodes\x18\x02 \x03(\v2\x0e.dn42_map.NodeR\x05nodes\x12$\n" +
	"\x05links\x18\x03 \x03(\v2\x0e.dn42_map.LinkR\x05linksB$Z\"github.com/iedon/dn42_map_go/protob\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_graph_proto_goTypes = []any{
	(*Node)(nil),       // 0: dn42_map.Node
	(*Centrality)(nil), // 1: dn42_map.Centrality
	(*Route)(nil),      // 2: dn42_map.Route
	(*IPv6)(nil),       // 3: dn42_map.IPv6
	(*Link)(nil),       // 4: dn42_map.Link
	(*Metadata)(nil),   // 5: dn42_map.Metadata
	(*Graph)(nil),      // 6: dn42_map.Graph
}
var file_graph_proto_depIdxs = []int32{
	2, // 0: dn42_map.Node.routes:type_name -> dn42_map.Route
	1, // 1: dn42_map.Node.centrality:type_name -> dn42_map.Centrality
	2, // 2: dn42_map.Node.routes_multicast:type_name -> dn42_map.Route
	3, // 3: dn42_map.Route.ipv6:type_name -> dn42_map.IPv6
	5, // 4: dn42_map.Graph.metadata:type_name -> dn42_map.Metadata
	0, // 5: dn42_map.Graph.nodes:type_name -> dn42_map.Node
	4, // 6: dn42_map.Graph.links:type_name -> dn42_map.Link
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_graph_proto_msgTypes[2].OneofWrappers = []any{
		(*Route_Ipv4)(nil),
		(*Route_Ipv6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
